[project]
name = "pybet2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi[standard-no-fastapi-cloud-cli]>=0.125.0",
    "sqlmodel>=0.0.29",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
